
services:
  - type: web
    name: api-fastweb-proxy
    runtime: python
    repo: https://github.com/icarocruuz/api-fastweb-proxy
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10001
    envVars:
      - key: PORT
        value: 10000
